### ISSUE TITLE
Build failed in Xcode

### ISSUE THREAD

**Issue by JerroldLee** [bluedaniel/Kakapo-native#1]
Build failed in Xcode, but don't know the reason

**Comment by bluedaniel** [comment]
I'll try cloning and building this from scratch tonight to see if I can replicate it.

**Comment by bluedaniel** [comment]
Yeah I'm not sure what happened but I've re-written some files and updated RN to 13.1, should be ok now.

React native webpack server seems to have problems with the latest RN so I've dropped it for now.
