### ISSUE TITLE
Loads 'Welcome to react native' screen.

### ISSUE THREAD

**Issue by MuruganDurai** [bluedaniel/Kakapo-native#2]
I used react-native start & run-android commands to run your wonderful app after cloned it. App deployed and loaded with default 'welcome to react native' screen using index.android.js not custom home screen. Is there any other configurations needs to be set to load app's home screen?

**Comment by MuruganDurai** [comment]
Replaced index.android.js code with below one, but got null issue at StatusbarIOS.setStyle,

import React from "react-native"; import {App} from "./src/containers";
React.AppRegistry.registerComponent('kakaponative', () => App);

**Comment by bluedaniel** [comment]
You can should be able to setup and run the Android environment just it says in the getting started docs - https://facebook.github.io/react-native/docs/getting-started.html#content

**Comment by MuruganDurai** [comment]
Hi, Since woking on android i removed ios related code. Thanks.
